### ISSUE TITLE
FortiusANT.exe

### ISSUE THREAD

**Issue by Timbertacxfortius** [WouterJD/FortiusANT#303]
Hi Wouter
No joy with FortiusANT .exe
2 x ANT+ dongles OK and VR interface detected/working
Are you able to see anything from this?
Cheers
Timber NZ

FortiusANT is open source and can be used freely.

Just for the fun of knowing where you all are training,
put yourself on the FortiusANT map by making yourself known
by leaving a message with name/location/trainer on
https://github.com/WouterJD/FortiusANT/issues/14

or visit the sponsoring page https://github.com/sponsors/WouterJD
---------------------------------------------------------------
09:49:05,782: Connected to Tacx Trainer T1932
09:49:06,225: Motor Brake Unit Firmware=0x1007 Serial= 2848 year=2011 type=T1941 Version2=2819 MotorBrake=True
09:49:06,332: FortiusAnt applies the MotorBrake power curve
Traceback (most recent call last):
  File "FortiusAnt.py", line 667, in <module>
  File "FortiusAnt.py", line 642, in mainProgram
  File "FortiusAnt.py", line 454, in ListenToChild
  File "FortiusAnt.py", line 129, in LocateHW
  File "FortiusAntBody.py", line 392, in LocateHW
  File "usbTrainer.py", line 455, in GetTrainer
  File "usb\core.py", line 974, in write
  File "usb\core.py", line 113, in wrapper
  File "usb\core.py", line 227, in setup_request
  File "usb\core.py", line 113, in wrapper
  File "usb\core.py", line 178, in managed_claim_interface
  File "usb\backend\libusb0.py", line 537, in claim_interface
  File "usb\backend\libusb0.py", line 447, in _check
usb.core.USBError: [Errno None] b'libusb0-dll:err [claim_interface] could not claim interface 0, win error: The requested resource is in use.\r\n'
[572] Failed to execute script FortiusAnt

**Comment by WouterJD** [comment]
Let's treat this issue with #301
