### ISSUE TITLE
Running FortiusAnt on Windows 10 does not work with BLE enabled; server.js crashes at virtual-trainer.js:21:11

### ISSUE THREAD

**Issue by WouterJD** [WouterJD/FortiusANT#360]
**Suggestions for the below problem, welcome!**

After installing node on Windows 10:
```
node hello.js
Node is installed!

node -v
v16.13.1

npm -v
8.1.2

```

Absence of a BLE-dongle is correctly detected:
```
C:\Github\WouterJD\FortiusANT\node>node server.js
C:\Github\WouterJD\FortiusANT\node\node_modules\@abandonware\bluetooth-hci-socket\lib\usb.js:91
    throw new Error('No compatible USB Bluetooth 4.0 device found!');

```

But running server.js with BLE-dongle results in a crash:
```
C:\Github\WouterJD\FortiusANT\node>node server.js
C:\Github\WouterJD\FortiusANT\node\node_modules\usb\usb.js:38
        this.__open()
             ^

Error: LIBUSB_ERROR_NOT_SUPPORTED
    at Device.usb.Device.open (C:\Github\WouterJD\FortiusANT\node\node_modules\usb\usb.js:38:7)
    at BluetoothHciSocket.bindUser (C:\Github\WouterJD\FortiusANT\node\node_modules\@abandonware\bluetooth-hci-socket\lib\usb.js:94:19)
    at BluetoothHciSocket.bindRaw (C:\Github\WouterJD\FortiusANT\node\node_modules\@abandonware\bluetooth-hci-socket\lib\usb.js:47:8)
    at Hci.init (C:\Github\WouterJD\FortiusANT\node\node_modules\bleno\lib\hci-socket\hci.js:110:35)
    at BlenoBindings.init (C:\Github\WouterJD\FortiusANT\node\node_modules\bleno\lib\hci-socket\bindings.js:97:13)
    at Bleno.<anonymous> (C:\Github\WouterJD\FortiusANT\node\node_modules\bleno\lib\bleno.js:49:22)
    at Bleno.emit (node:events:390:28)
    at _addListener (node:events:433:14)
    at Bleno.addListener (node:events:487:10)
    at new VirtualTrainer (C:\Github\WouterJD\FortiusANT\node\virtual-trainer.js:21:11) {
  errno: -12
}
```

**Comment by WouterJD** [comment]
A BLE-dongle was in the systems USB-port and zadig run to replace the driver.
This worked.

THEN a USB-hub was added and the dongle moved there; then zadig must be run again!
So my problem is now solved, thanks to @marcoveeneman's bright remark.
And I will add to the manual
